path:
  to_image: "/home/danila/Pictures/bots/market/"
messages:
  responses:
    start: "Для того чтобы бот показал вам результаты событий перешлите сообщение из бота @TonarchyBot с событием"
    new_event: "Напишите текст события (без вариантов)"
    first_event: "Напишите изменение ресурсов если выбрать ПЕРВЫЙ вариант.\nПример:\nИнтриги: 70 → 95\nЗнания: 65 → 75\nСредства: 20 → 10"
    first_event_failed: "Первый вариант уже существует"
    second_event: "Напишите изменение ресурсов если выбрать ВТОРОЙ вариант.\nПример:\nИнтриги: 70 → 95\nЗнания: 65 → 75\nСредства: 20 → 10"
    second_event_failed: "Второй вариант уже существует"
  errors:
    undefinedCommand: Такой команды не существует
  buttons:
    skip: "Пропустить"
    add: "Добавить новое событие"
    cancel: "Отменить"
    
